### ISSUE TITLE
Bar gets completed when using SetTotal with triggerComplete parameter set to true

### ISSUE THREAD

**Issue by vincedupuis** [vbauerster/mpb#104]
When setting the total dynamically with SetTotal,
if the triggerComplete parameter is set to true,
the bar will be set to complete right away.

**Comment by TomerH** [comment]
@vbauerster Hey I was encountered with this issue also, unless I understood it wrong.
If I'm using dynamic total should it mark the bar as completed automatically when current == total? or I need to do it manually.
What the purpose of triggerComplete parameter? sounds like a bug..

Thanks :)

**Comment by vbauerster** [comment]
This is not a bug, it's intended behavior.
Refer to [_examples/dynTotal/main.go](https://github.com/vbauerster/mpb/blob/master/_examples/dynTotal/main.go)
