### ISSUE TITLE
The log will be overwritten while the progress bar is printed

### ISSUE THREAD

**Issue by zhijian-pro** [vbauerster/mpb#105]
The log will be overwritten while the progress bar is printed.
How to set not to overwrite the log, but to move the progress bar down one line?
```
package main

import (
	"time"

	"github.com/sirupsen/logrus"

	"github.com/vbauerster/mpb/v7"
	"github.com/vbauerster/mpb/v7/decor"
)

var logger *logrus.Logger

func main() {
	logger = logrus.New()
	total := 10000
	p := mpb.New(mpb.WithWidth(64), mpb.WithOutput(logger.Writer()))
	b := p.AddBar(0, // disable triggerComplete
		mpb.PrependDecorators(
			decor.Name("test count: ", decor.WCSyncWidth),
			decor.CountersNoUnit("%d / %d"),
		),
		mpb.AppendDecorators(
			decor.OnComplete(decor.Percentage(decor.WC{W: 5}), "done"),
			decor.OnComplete(
				decor.AverageETA(decor.ET_STYLE_GO, decor.WC{W: 6}), "",
			),
		),
	)
	b.SetTotal(int64(total), false)

	for {
		logger.Infof(time.Now().String())
		time.Sleep(1 * time.Second)
		b.Increment()
	}
	b.SetTotal(0, true)
}

```

**Comment by zhijian-pro** [comment]
What you say is also reasonable, but undeniably, progress bar and log record both have prompt function on terminal.And logs can express information that progress bars cannot replace. For example, an exception occurs in the ninth order. This exception only affects the ninth order, not the others, so the application should continue to run, but it should also be very obvious to the user that there is a problem in the ninth order.
You can also see that many people have feedback on similar problems under many progress bar frameworks, which shows that this demand is common.

**Comment by venth** [comment]
I believe that my case is similar as @zhijian-pro. I'm looking for a `multi progress bar` which is capable of tracing a progress and present information about matching records. Such a solution exists in [indicatif](https://github.com/console-rs/indicatif). `indicatif` exposes a function [println](https://docs.rs/indicatif/latest/indicatif/struct.ProgressBar.html#method.println) which prints a message above a single or multi progress bar.

What do you think @vbauerster about extending current progress bar api by supporting of printing a message?

**Comment by vbauerster** [comment]
If you need to print something above a bar while it's running, please refer to [this](https://github.com/vbauerster/mpb/blob/master/_examples/barExtenderRev/main.go) example.

> Such a solution exists in [indicatif](https://github.com/console-rs/indicatif). indicatif exposes a function [println](https://docs.rs/indicatif/latest/indicatif/struct.ProgressBar.html#method.println) which prints a message above a single or multi progress bar.

You forgot to count unresolved issues related to that feature.

**Comment by venth** [comment]
Thanks for the answer and pointing out the example. I’ll take a look.

`You forgot to count unresolved issues related to that feature.`

That’s so true for both - forgetting and number of issues  :) :) some of the issues I’ve omitted by creating a printing sequence. So it’s done in one thread.

For now, I’ve got tired of `borrowing` and `moving` in rust and went to golang. That’s why this library got my attention.

**Comment by wohenbushuang** [comment]
> If you need to print something above a bar while it's running, please refer to [this](https://github.com/vbauerster/mpb/blob/master/_examples/barExtenderRev/main.go) example.

It's complicated and seems the contents should be predefined. It will print everytime the progressbar refreshed, which may not the same as what we need (the behaviors like `npm install`).

**Comment by vbauerster** [comment]
Implemented in v8.
https://pkg.go.dev/github.com/vbauerster/mpb/v8#Progress.Write
