### ISSUE TITLE
Replace internal github imports with gopkg.in

### ISSUE THREAD

**Issue by vmarkovtsev** [vbauerster/mpb#11]
Currently, `mpb`'s implementation imports from github. Thus if you exec `go get gopkg.in/vbauerster/mpb.v3` you actually fetch the project twice. Besides, the second copy from github is not synced with v3 release, and the project may become unusable.

Another side effect is that if you import `mpb` like that:

```
import (
  "gopkg.in/vbauerster/mpb.v3"
  "gopkg.in/vbauerster/mpb.v3/decor"
)
```

The build fails because `"gopkg.in/vbauerster/mpb.v3"` imports `"github.com/vbauerster/mpb/decor"` and the types from `decor` do not match:

```
cannot use "gopkg.in/vbauerster/mpb.v3/decor".DynamicName(func literal, 10, 0) (type "gopkg.in/vbauerster/mpb.v3/decor".DecoratorFunc) as type "github.com/vbauerster/mpb/decor".DecoratorFunc in argument to mpb.PrependDecorators
```

So to actually build the examples, we need

```
import (
  "gopkg.in/vbauerster/mpb.v3"
  "github.com/vbauerster/mpb/decor"
)
```

which does not make any sense to me. So I propose to rediect the internal imports to `gopkg.in`, as the rest of the folks do.

**Comment by vbauerster** [comment]
First of all, thank you for reporting this.
I'm afraid changing internal imports to gopkg.in, will brake code for [those](https://godoc.org/github.com/vbauerster/mpb?importers) who importing directly from github. In other words it will force everybody to import from gopkg.in. Gopkg.in was good (and maybe only) option in early days of Go, but nowadays there are plenty of package managers available out there. IMO its better rely on [dep](https://github.com/golang/dep) management tools to fix package versions. I will certainly update readme warning users about gopkg.in.
