### ISSUE TITLE
Display text instead of progress bar

### ISSUE THREAD

**Issue by Wulfheart** [vbauerster/mpb#112]
Hello,

similar to [yacspin](https://github.com/theckman/yacspin) (which does not support parallel spinners) I would like to have a text displayed instead of a progress bar. Is this possible with this library and if so, how can this be achieved?

Thanks in advance.

**Comment by vbauerster** [comment]
Hi!

It is possible. You have to implement your own [Filler](https://github.com/vbauerster/mpb/blob/c0272e6db17a320112702aaf1bd3507bb75f7edb/bar_filler.go#L13), or you can use [NopStyle](https://github.com/vbauerster/mpb/blob/c0272e6db17a320112702aaf1bd3507bb75f7edb/bar_filler_nop.go#L10) implementation to not show bar at all.

**Comment by Wulfheart** [comment]
@vbauerster thanks for your response. 
Is it also possible to display a spinner? I don’t think so, or is it possible?

**Comment by vbauerster** [comment]
Check this one:
https://github.com/vbauerster/mpb/blob/master/_examples/spinnerBar/main.go
