### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by anacrolix** [vbauerster/mpb#115]
When running with 100s of bars (most of which "complete" and stop being updated), memory begins to climb. This behaviour remains even if I Abort my Bars.

![image](https://user-images.githubusercontent.com/988750/189482431-db0297d1-a0a9-4175-ad2f-a0869b1877e7.png)

There's a corresponding increase in CPU use too, 

![pprof001](https://user-images.githubusercontent.com/988750/189482551-fcb9baf9-5e53-4916-b465-56cdefe545b3.svg).

Thanks for the cool library.

**Comment by vbauerster** [comment]
Thanks for reporting! I think I know why is that.

**Comment by vbauerster** [comment]
Can you please test with head master? Should be fixed.

**Comment by vbauerster** [comment]
Just for reference, the bug introduced in 11d342b48a6a6fae11cce739aca22c825bc1fafa. It appears only when bars don't fit to terminal, i.e. number of bars are greater than terminal height.

**Comment by anacrolix** [comment]
I'm not sure I can test this now, I've switched to another library for the progress bars and they're deeply integrated into some other changes.

**Comment by anacrolix** [comment]
I went back and tried it against master. I cannot reproduce either the memory or CPU problems anymore!
