### ISSUE TITLE
Panic when calling bar.DecoratorEwmaUpdate inside goroutine

### ISSUE THREAD

**Issue by DeltaLaboratory** [vbauerster/mpb#117]
When i calling bar.DecoratorEwmaUpdate after calling bar.Increment() inside goroutine, it panics.

I am using go1.19.1, windows/amd64.

There is some example code that seems cause panic...

https://go.dev/play/p/2oSrMdlHcEF

**Comment by vbauerster** [comment]
I've updated api to fix this. You need to call `bar.EwmaIncrement(time.Since(goRoutineStartTime))` instead.
https://go.dev/play/p/pYIHUmWzo5O

**Comment by DeltaLaboratory** [comment]
The patch fixed the problem.
Thank you!
