### ISSUE TITLE
if not a TTY, mpb still output control characters

### ISSUE THREAD

**Issue by MichaelMure** [vbauerster/mpb#119]
I may have done something slightly wrong or unexpected by using `stdout` for my progress bars instead of `stderr`, but I noticed that when redirecting the output to a file, `mpb` was not printing the progress bar itself, but still printed the control characters to manipulate the (non-existent) terminal. This resulted in those outputs in my file:

```
^[[2A^[[J

^[[2A^[[J

^[[2A^[[J

^[[2A^[[J

^[[2A^[[J

^[[2A^[[J

^[[2A^[[J

^[[2A^[[J

^[[2A^[[J

^[[2A^[[J

....
```

It's not a huge problem, but that still looks like a bug.

**Comment by vbauerster** [comment]
That has been fixed in `v8.2.0`. If output is not a TTY no any write will occur unless [WithAutoRefresh](https://pkg.go.dev/github.com/vbauerster/mpb/v8#WithAutoRefresh) option is set.

https://github.com/vbauerster/mpb/blob/3907ae91fd525b077c354b93d3b39ac1c75e533b/progress_test.go#L248
