### ISSUE TITLE
Leading white space not removable?

### ISSUE THREAD

**Issue by nilsbeck** [vbauerster/mpb#123]
Hey, 
i stumbled upon a leading white space that I cannot seem to remove. Here is an example:

```
frames := []string{"🐰", "🐰", "🥕", "🥕"}
barfiller := mpb.SpinnerStyle(frames...)
bar := progress.New(int64(-1),
	barfiller.PositionLeft(),
	mpb.BarRemoveOnComplete(),
	mpb.BarFillerClearOnComplete(),
	mpb.BarWidth(2),
	mpb.AppendDecorators(
		decor.Name(title),
	),
)
```

What do I see?
With this code I see bunny and carrot with a leading white space. When I set `BarWidth` to `1` there is only a white space shown and bunny/carrot are gone.

What do I expect to see?
In general the leading white space should be gone and thus, setting the `BarWidth` to `1` shows bunny/carrot.

Or am I doing something fundamentally wrong here?

**Comment by vbauerster** [comment]
Try this one [BarFillerTrim](https://pkg.go.dev/github.com/vbauerster/mpb/v8#BarFillerTrim).

**Comment by nilsbeck** [comment]
Oh cool. Not sure how I missed this!
Fixes my problem!
