### ISSUE TITLE
Bar Positioning

### ISSUE THREAD

**Issue by elbaro** [vbauerster/mpb#13]
My goroutines dynamically create/remove bars, and their order on the screen depend on the order of execution (which is random). Is it possible to give a specific order between bars?

If not, can we add something like `p.AddBar(priority=int)`, or to prevent a frequent move, `p.AddBar(absolute_row=int)`.

**Comment by vbauerster** [comment]
You can achieve a specific order by utilising bar sorting. See sort [example](https://github.com/vbauerster/mpb/blob/master/examples/sort/main.go).

**Comment by vbauerster** [comment]
New method [UpdateBarPriority](https://godoc.org/github.com/vbauerster/mpb#Progress.UpdateBarPriority) has been added, to make it simpler.
