### ISSUE TITLE
SetTotal not working with complex bar

### ISSUE THREAD

**Issue by nabbar** [vbauerster/mpb#131]
Hello,

First of all thank you for your library, it's great :)

I have a problem with the latest version v8 and the "complex bar".
This issue was not found in V5. (I just upgraded to V8, but this problem seems to be present in v6, v7 too).

I made an example here: [Go Playground](https://go.dev/play/p/9YydRugvfK5)

Here's the problem:
- start a new bar with a total of 0
- add several bars like this:
      - a total of 0 for some bars, and a value for others
      - don't forget the BarQueueAfter option with the previous bar in parameters

Make a loop for each bar:
- set bar total with trigger completion to false
- advance the bar (as a complex example in this reference)

The bar with a total set at creation will work normally but the bar created with 0 as total will have 0 when executed, even after a SetTotal.

When I analyze, not all complex bars have started, this value has a false value: bState.triggerComplete. But once the first bar is finished, this value will have real value for all the others.

I think the problem comes from this test which is triggered once a bar is finished and remains valid for all the others.
![image](https://github.com/vbauerster/mpb/assets/19818221/2875bad4-db23-48e2-a76c-6800fff168ce)

https://github.com/vbauerster/mpb/blob/master/bar.go#L211

It's possible that I missed something, unless it's a bug or expected behavior (but in this case, I didn't see it in the migration details)

**Comment by vbauerster** [comment]
Hi!
In short calling [EnableTriggerComplete](https://github.com/vbauerster/mpb/blob/795c4be972927bf2fd4509bc2c919dd8ba266e0a/bar.go#L184) disables setting total. For more please refer to:
https://github.com/vbauerster/mpb/blob/fab44347b86bef9303c52067ebfb1b8831acacd1/bar_test.go#L70
https://github.com/vbauerster/mpb/blob/fab44347b86bef9303c52067ebfb1b8831acacd1/bar_test.go#L101
