### ISSUE TITLE
AppendDecorators display wrong

### ISSUE THREAD

**Issue by pierre-emmanuelJ** [vbauerster/mpb#26]
The following code represents my progress bar
```Golang
p.AddBar(fileInfo.Size(),
			mpb.PrependDecorators(
				// simple name decorator
				decor.Name(task.string),
				// decor.DSyncWidth bit enables column width synchronization
				decor.Percentage(decor.WCSyncSpace),
			),

			mpb.AppendDecorators(
			 	// replace ETA decorator with "done" message, OnComplete event
			 	decor.OnComplete(
			 		// ETA decorator with ewma age of 60
			 		decor.EwmaETA(decor.ET_STYLE_GO, 60), "done",
			 	),
			 ),
		)
```
this is the output during progress:

```
 an example 4 % [=>------------------------------------------------------------] 0s
```
then when it is done
```
an example 100 % [=============================================] done
```

Why during the progress ETA is displayed and why is doesn't working ?

if I remove this part of code:
```Golang
mpb.AppendDecorators(
			 	// replace ETA decorator with "done" message, OnComplete event
			 	decor.OnComplete(
			 		// ETA decorator with ewma age of 60
			 		decor.EwmaETA(decor.ET_STYLE_GO, 60), "done",
			 	),
			 ),
```
It's works good, but `done` message at the end is not displayed naturally

**Comment by vbauerster** [comment]
Hi! How do you increment? If it is io operation, do you use [ProxyReader](https://github.com/vbauerster/mpb/blob/master/examples/io/single/main.go#L58)?

**Comment by pierre-emmanuelJ** [comment]
HI! thank you very much for your response.
Sorry for this late response!

Yes I use [ProxyReader](https://github.com/vbauerster/mpb/blob/master/examples/io/single/main.go#L58)

**Comment by vbauerster** [comment]
Try higher number for EwmaETA decorator, if issue is still relevant.

**Comment by vbauerster** [comment]
It's hard to say what's wrong with your code, provided snippet says nothing. [Example](https://github.com/vbauerster/mpb/blob/master/examples/io/single/main.go) which is using EwmaETA decorator, works as expected in `v3.3.2`:
https://asciinema.org/a/UcxMzSPNdlyRMckkBgNnZQ806

**Comment by pierre-emmanuelJ** [comment]
It's work very nice ETA too BUT:
when I want to replace the time with "done" at the end with this following code:
```Golang
mpb.AppendDecorators(
			 	// replace ETA decorator with "done" message, OnComplete event
			 	decor.OnComplete(
			 		// ETA decorator with ewma age of 60
			 		decor.EwmaETA(decor.ET_STYLE_GO, 60), "done",
			 	),
			 ),
``` 
So when I add this code Time doesn't working anymore example:
https://asciinema.org/a/0zx1oHlqpDJuIash5eQaXN8Os

and if I add this code:
```Golang
mpb.AppendDecorators(
                                decor.AverageETA(decor.ET_STYLE_GO),
			 	// replace ETA decorator with "done" message, OnComplete event
			 	decor.OnComplete(
			 		// ETA decorator with ewma age of 60
			 		decor.EwmaETA(decor.ET_STYLE_GO, 60), "done",
			 	),
			 ),
``` 
I get this:
https://asciinema.org/a/PJejQBd8T3DiPKyU0WfJH19Mw

Then if I remove the `decor.OnComplete` I can do what I want perfectly

**Comment by vbauerster** [comment]
Can you please paste full code sample where it doesn't work for you? As I mentioned before, example code has the same combination: `decor.EmwaETA` wrapped inside `decor.OnComplete` and both do work.

**Comment by pierre-emmanuelJ** [comment]
This is the full code:
https://github.com/exoscale/cli/blob/master/cmd/sos_upload.go
I have explained to you just earlier the different cases if you change the code.

Thank you

**Comment by vbauerster** [comment]
Ok, if I understood correctly, your problem is when you wrap any eta decorator into `OnComplete`, you got zero value `0s` always. And when you use it without `OnComplete` it is ok. Is that correct?
If so, I cannot reproduce such behaviour.
Here I use both eta wrapped into `OnComplete`:
```go
	bar := p.AddBar(size,
		mpb.PrependDecorators(
			decor.CountersKibiByte("% 6.1f / % 6.1f"),
		),
		mpb.AppendDecorators(
			decor.Name("ewma: "),
			decor.OnComplete(decor.EwmaETA(decor.ET_STYLE_MMSS, float64(size)/2048), "done!"),
			decor.Name(" avg: "),
			decor.OnComplete(decor.AverageETA(decor.ET_STYLE_GO), "done!"),
			decor.Name(" ] "),
			decor.AverageSpeed(decor.UnitKiB, "% .2f"),
		),
	)
```
The output as expected:
https://asciinema.org/a/dUskQrJ1JnHp9qxI0miYXLSop

**Comment by pierre-emmanuelJ** [comment]
yes it was that 👍 
🎉 OKAY I have solved my problem by using:
`decor.OnComplete(decor.AverageETA(decor.ET_STYLE_GO), "done!"),` in `AppendDecorators`
instead of:
`decor.OnComplete(decor.EwmaETA(decor.ET_STYLE_GO, 60), "done"),` in `AppendDecorators`

Do you think it's come from the proxy reader?

**Comment by vbauerster** [comment]
> Do you think it's come from the proxy reader?

No. I think it is how underlying [ewma](https://github.com/VividCortex/ewma) lib works.
Wen you use age > 0, it uses [VariableEWMA](https://github.com/VividCortex/ewma#variableewma), which requires some "warmup", before it displays something other than zero.

**Comment by pierre-emmanuelJ** [comment]
> Wen you use age > 0, it uses [VariableEWMA](https://github.com/VividCortex/ewma#variableewma), which requires some "warmup", before it displays something other than zero.

I have tried with very big file to prevent the "warmup"

## Thank you very much for your help 😸

**Comment by vbauerster** [comment]
You're welcome! By the way,  I don't recommend passing full size to [EwmaETA](https://godoc.org/github.com/vbauerster/mpb/decor#EwmaETA) age param, instead divide your size to something other than zero ;) Good candidate is buffer size.

**Comment by vbauerster** [comment]
@pierre-emmanuelJ 
This [line](https://github.com/exoscale/cli/blob/master/cmd/sos_upload.go#L116) seems to be part of the culprit. You suppose to pass a wrapped (proxy) reader everywhere, where `io.Reader` is expected, otherwise there is no guarantee that `EwmaETA` will work at all.
