### ISSUE TITLE
injecting custom fillBar

### ISSUE THREAD

**Issue by greut** [vbauerster/mpb#29]
Hi,

We are using mpb and would like have some spinners rather than progress bars. Do you see an easy way to inject a strategy for a custom `s.fillBar(width)` ?

**Comment by vbauerster** [comment]
Hi,
well spinners have no notion of progress indicator, unless they represent something indeterministic.
So just curious what is your use case?

**Comment by greut** [comment]
[wow](https://github.com/gernest/wow) has super nice spinners, but doesn't have any grouping facility. On the other hand, mpb works well for launching a bunch of tasks. We currently cheat and create fake progress bars :)

**Comment by vbauerster** [comment]
Please check [Progress.AddSpinner](https://godoc.org/github.com/vbauerster/mpb#Progress.AddSpinner).

**Comment by vbauerster** [comment]
You can inject custom bar [Filler](https://godoc.org/github.com/vbauerster/mpb#Filler) to [Progress.Add](https://godoc.org/github.com/vbauerster/mpb#Progress.Add).
