### ISSUE TITLE
How to make decor.Elapsed of multi bars calculate independently?

### ISSUE THREAD

**Issue by yech1990** [vbauerster/mpb#30]
I want to calculate the elapsed time of each progress bar, and output the time on 
AppendDecorators.  But the time of finished bar keep growing, even when the progress of this bar is finished. Thus, the final elapsed time is always the same.

BTW, is it possible to write a progress bar group that dropout each bar when it is finished. But keep  the final completed one.

**Comment by vbauerster** [comment]
You're right, elapsed continue to tick after bar has been completed. I've fixed this in e87645f.

Yes it is possible to remove bar on complete. Your friends are:

- [complex example](https://github.com/vbauerster/mpb/blob/master/examples/complex/main.go)
- [BarRemoveOnComplete](https://godoc.org/github.com/vbauerster/mpb#BarRemoveOnComplete)
- [BarClearOnComplete](https://godoc.org/github.com/vbauerster/mpb#BarClearOnComplete)
- [BarReplaceOnComplete](https://godoc.org/github.com/vbauerster/mpb#BarReplaceOnComplete)

If default decorators doesn't meet your needs, it is easy to implement a custom one by satisfying [Decorator](https://godoc.org/github.com/vbauerster/mpb/decor#Decorator) interface.
