### ISSUE TITLE
Request: Performance improvements

### ISSUE THREAD

**Issue by nilsocket** [vbauerster/mpb#31]
When 4 bars where updated with nearly 8 goroutines each, cpu usage have raised from 20% to 75%,.

After removing  progress bar,  same computation took less than  25% cpu usage.

**Comment by vbauerster** [comment]
Can you please provide a go buildable code sample, where issue can be reproduced?
My guess is that you do high computation in custom decorators, if you do so, then indeed that sounds plausible.

**Comment by nilsocket** [comment]
I'm sorry, I checked once again, It's my program which is inconsistent.

Thank you.
