### ISSUE TITLE
How do I vendor this library?

### ISSUE THREAD

**Issue by vrothberg** [vbauerster/mpb#36]
Hi,

first off, thanks for this great library. I am quite excited about it!

I am working on porting our tools to use it (see https://github.com/containers/image/pull/581) but I am currently stuck with the below issue.

We need to vendor the code and use `github.com/LK4D4/vndr` for managing the dependencies. So far I tried vendoring github.com/vbauerster/mpb directly and also doing dance with gopkg.in/vbauerster/mpb.v4/ as shown in the error below. None of it succeeded.

Can you shed some light on my issue?

```
vendor/gopkg.in/vbauerster/mpb.v4/progress.go:13:2: cannot find package "github.com/vbauerster/mpb/v4/cwriter" in any of:  
        /home/valentin/go/src/github.com/containers/skopeo/vendor/github.com/vbauerster/mpb/v4/cwriter (vendor tree)       
        /usr/lib/golang/src/github.com/vbauerster/mpb/v4/cwriter (from $GOROOT)
        /home/valentin/go/src/github.com/vbauerster/mpb/v4/cwriter (from $GOPATH)
vendor/gopkg.in/vbauerster/mpb.v4/bar.go:14:2: cannot find package "github.com/vbauerster/mpb/v4/decor" in any of:         
        /home/valentin/go/src/github.com/containers/skopeo/vendor/github.com/vbauerster/mpb/v4/decor (vendor tree)         
        /usr/lib/golang/src/github.com/vbauerster/mpb/v4/decor (from $GOROOT)
        /home/valentin/go/src/github.com/vbauerster/mpb/v4/decor (from $GOPATH)
vendor/gopkg.in/vbauerster/mpb.v4/bar_filler.go:9:2: cannot find package "github.com/vbauerster/mpb/v4/internal" in any of:
        /home/valentin/go/src/github.com/containers/skopeo/vendor/github.com/vbauerster/mpb/v4/internal (vendor tree)      
        /usr/lib/golang/src/github.com/vbauerster/mpb/v4/internal (from $GOROOT)
        /home/valentin/go/src/github.com/vbauerster/mpb/v4/internal (from $GOPATH)
```

**Comment by vbauerster** [comment]
Hi!
You're welcome )

What version of go do you use?

`v4` is a go module and for any go module minimum go version requirement is 1.10.3+ (or 1.9.7+). Those min versions still allow to import a module without a `v2+` suffix.

If updating go version is not an option for you, so have your dependency manager to use older [mpb v3.3.4](https://github.com/vbauerster/mpb/releases/tag/v3.3.4).

PS: I encourage you to use latest go, and switch to [modules](https://www.youtube.com/watch?v=aeF3l-zmPsY).

**Comment by vrothberg** [comment]
> What version of go do you use?

I'm on go1.11.5.

> `v4` is a go module and for any go module minimum go version requirement is 1.10.3+ (or 1.9.7+). Those min versions still allow to import a module without a `v2+` suffix.

That explains it, thanks!

> If updating go version is not an option for you, so have your dependency manager to use older [mpb v3.3.4](https://github.com/vbauerster/mpb/releases/tag/v3.3.4).
> 
> PS: I encourage you to use latest go, and switch to [modules](https://www.youtube.com/watch?v=aeF3l-zmPsY).

We are planning to transition to go modules but we are very conservative in this regard. Go modules will be stable with go1.12 but many users of our library are still running older versions of go.

Thanks a lot for your quick reply! I'll try out vendoring v3.3.4 :)

**Comment by vrothberg** [comment]
v3.3.4 works. Thanks a lot!
