### ISSUE TITLE
Don't print bar

### ISSUE THREAD

**Issue by vrothberg** [vbauerster/mpb#39]
Hi,

we're currently using v3.3.4 as we're not (yet) using Go mod. Is there a way to create a new bar that doesn't display a progress bar?

What we're trying to achieve is first print some kind of "placeholder" bar that is later being replaced with another bar if needed. Imagine it as follows:
```
Bar 1: waiting for something to happen
Bar 2: performing work [=======> ]
```
At a later point, we want to replace `Bar 1` with something similar to `Bar 2`.

**Comment by vbauerster** [comment]
Hi,

Well there is an option [BarReplaceOnComplete](https://github.com/vbauerster/mpb/blob/fbc6960bc81e6c0ef7f1d32f12923934f1f5836f/bar_option.go#L83). With this option you kind a point to a running bar after which it should start. Given `bar2 := p.AddBar(total, mpb.BarReplaceOnComplete(bar1))`, `bar2` will not start until `bar1` completes. Complex example uses this approach. Hope this helps.

**Comment by vrothberg** [comment]
Hi @vbauerster,

thanks for your quick reply!

> Well there is an option BarReplaceOnComplete. With this option you kind a point to a running bar after which it should start. Given bar2 := p.AddBar(total, mpb.BarReplaceOnComplete(bar1)), bar2 will not start and print until bar1 completes. Complex example uses this approach. Hope this helps.

We're using that already and this part works fine. But the problem is that we don't find a way to avoid printing a progress bar.

`BarReplaceOnComplete()` requires `BarRemoveOnComplete()` to be set on the running bar which complicates it a bit. The inital though was to create a bar with `BarClearOnComplete` and `onComplete` messages to basically clear the progress bar at creation. But if we want to replace it at a later point we have to call `BarRemoveOnComplete()` which will effectively remove it at creation time.

What we fail to achieve is the following:
1. Create a bar without a progress bar (e..g, `Bar 1: some message`) which just serves as a placeholder for a future bar
2. Wait for an event while still displaying bar 1)
3. Depending on the event, replace bar 1) with a new bar

**Comment by vbauerster** [comment]
```go
package main

import (
	"fmt"
	"io"
	"time"

	"github.com/vbauerster/mpb/v4"
	"github.com/vbauerster/mpb/v4/decor"
)

func main() {
	dummyBar := func(w io.Writer, width int, st *decor.Statistics) {
		fmt.Fprint(w, "Bar 1: waiting for an event")
	}

	p := mpb.New()
	bar1 := p.Add(0,
		mpb.FillerFunc(dummyBar),
		mpb.BarRemoveOnComplete(),
		mpb.TrimSpace(),
	)

	// simulating some event
	event := make(chan struct{})
	time.AfterFunc(5*time.Second, func() {
		bar1.SetTotal(0, true)
		close(event)
	})

	bar2 := p.AddBar(800,
		mpb.PrependDecorators(
			decor.Name("Bar 2:"),
		),
	)

	go func() {
		for !bar2.Completed() {
			bar2.Increment()
			time.Sleep(50 * time.Millisecond)
		}
	}()

	// bar3 waits for an event to replace bar1
	bar3 := p.AddBar(600,
		mpb.BarParkTo(bar1),
		mpb.PrependDecorators(
			decor.Name("Bar 1:"),
		),
	)

	go func() {
		<-event
		for !bar3.Completed() {
			bar3.Increment()
			time.Sleep(60 * time.Millisecond)
		}
	}()

	p.Wait()
}
```
Can you please run this snippet with latest v4? Is this what you want?

**Comment by vrothberg** [comment]
> Can you please run this snippet with latest v4? Is this what you want?

Yes, that's exactly the behavior we're looking for. I assume that the critical part is the `FillerFunc(..)` support? Thank you so much for your time and help. I really appreciate it.

I know I am asking a lot, but is there some way to offer v4 as a non-go-mod library? Most (nearly all) projects in the containers ecosystem are using the old way, and our current tooling is built around `vndr`. My personal estimation is that `go mod` will start being used there next year.

**Comment by vbauerster** [comment]
I'll check when I have some time, but not promising. 😎
If you can't wait, fork and edit could be a viable option for you.

**Comment by vbauerster** [comment]
> I know I am asking a lot, but is there some way to offer v4 as a non-go-mod library? Most (nearly all) projects in the containers ecosystem are using the old way, and our current tooling is built around vndr. My personal estimation is that go mod will start being used there next year.

I can't simply remove `v4` from import path, as it will break current module. Actually `v4` still can be used as a non-module with Go 1.10.3+ (or Go 1.9.7+). There must be problem with your vendor tool.

> I assume that the critical part is the FillerFunc(..) support?

You're right. The only feasible way is to port this impl into its own v3 branch. That way you'll be able to update with your vendor tool.

**Comment by vbauerster** [comment]
@vrothberg You should be able to run the snippet with [v3.4.0](https://github.com/vbauerster/mpb/releases/tag/v3.4.0). Can you please check?

**Comment by vrothberg** [comment]
Your message just arrived at the right moment. I was trying to work around with `vndr` and a relative symbolic link that would have certainly caused issues for downstream packagers.

I tried v3.4.0 and it does exactly what we need. @vbauerster, thank you so much! I am incredibly thankful for your help and support.

**Comment by vrothberg** [comment]
I am closing the issue as v3.4.0 allows us to achieve what we need.
