### ISSUE TITLE
Bars get duplicated when terminal shows less lines than number of bars

### ISSUE THREAD

**Issue by RobiNino** [vbauerster/mpb#40]
Hi,
Thanks for your library and all your work!

Im running mpb v4.6.0 on macOS.
I tried running the stress example and it seems that when the number of lines displayed in the terminal (a matter of font & window size) is lower than the number of bars, the first bars get duplicated. 

For example, when running the example with the default 32 bars, while terminal displays less than 30 lines:
last lines printed:
![image](https://user-images.githubusercontent.com/43318887/55180257-e4aa8900-5191-11e9-840c-2fc2e8886300.png)
first lines printed:
![image](https://user-images.githubusercontent.com/43318887/55180430-4a971080-5192-11e9-8cf3-5e3cbcdf5f3e.png)

Please correct me if I'm doing something wrong, or it is a known limitation I'm unaware of.
Thanks!

**Comment by vbauerster** [comment]
Hi, you're welcome.
In short, this is how [ANSI Escape sequences](http://ascii-table.com/ansi-escape-sequences.php) work. Cursor is moved up by number of bars without considering terminal's height (lines). Maybe it's possible to fix by acquiring raw terminal mode, but it will complicate things. So yes this is kind of limitation. Pull requests are welcomed.
Do you really need to display so many progress bars?

**Comment by RobiNino** [comment]
I understand. I'll try looking into it in my next free time.

For now, we don't need to display that many progress bars simultaneously, however this limitation also affects completed bar that weren't removed. I guess we will have to remove all completed bars. 

I'm closing this issue, feel free to reopen it if you want the limitation displayed.
Thanks for the response and info!
