### ISSUE TITLE
Questions: Bar extension, Logging

### ISSUE THREAD

**Issue by RobiNino** [vbauerster/mpb#41]
Hi again! 🙂 
A few questions if I may:

1. Is there an option to extend the bar such that the progress bar is printed on the 2nd line, while a static string on the first? 
I have tried:
- Passing a `decor.Name("name\n")`, but that gets the first line duplicated.
- Using `p.Add()` with a filler that prints a string as the 2nd argument, and a  
 `mpb.BarExtender()` with a bar as filler as a BarOption. Both lines are duplicated.

2. We would like to print logs to the same out while bars are running. Since these logs interfere with the bars, we thought about printing them as completed bars. 
Is adding a completed bar even possible, or do we have to increment once? Do you happen to have a better suggestion to doing so (not as a decorator to an existing bar, as the logs are not related to a specific bar)?

Thanks a lot in advance!

**Comment by vbauerster** [comment]
I suppose you're trying to achieve something like [this](https://asciinema.org/a/MghRNaatfkCeCUCfcNzQmv7wx)?

**Comment by RobiNino** [comment]
We are trying to achieve something like the following, where logs can be printed in between bars, and the bars description comes above it instead of on its left / bellow it:

Log #0
Log #1
Some bar #1:
[==================================================================] 100 %
Log #2
Log #3
Log #4
Log #5
Some bar: #2
[==================================================================] 100 %
Log #6
Log #7
Log #8
Log #9

Thanks

**Comment by vbauerster** [comment]
Ok, if you need to print some arbitrary text above a bar while it is running, you can add your [Filler](https://godoc.org/github.com/vbauerster/mpb#Filler) implementation. I've included the snippet in my previous reply, so you can figure out how to manipulate with custom Filler implementation.
> Is adding a completed bar even possible, or do we have to increment once?

You can complete bar, right after adding like:
```go
p.Add(0, yourFiller).SetTotal(0, true)
```

**Comment by RobiNino** [comment]
Thanks.
While this indeed matches our visual requirement, considering #40 and a large number of logs/bars, the bars will have to be removed so the logs cannot be left visible during the whole runtime (and after).

I guess there is no way around logging to log files, so thats what we'll do.
Thanks a lot for your time and effort!
