### ISSUE TITLE
Possible to have an IncrBy that takes in64 as input please?

### ISSUE THREAD

**Issue by sethkor** [vbauerster/mpb#42]
This is a feature request.

Is it possible to have an IncrBy that takes in64 as input please?

I'm working with file sizes and the ProxyReader doesn't work for me as I want to also do an ETA based on bytes processed.

Thanks

**Comment by vbauerster** [comment]
Added [IncrInt64](https://godoc.org/github.com/vbauerster/mpb#Bar.IncrInt64).
