### ISSUE TITLE
GoDoc comment for func EwmaSpeed is incorrect

### ISSUE THREAD

**Issue by sethkor** [vbauerster/mpb#43]
The method signature has age but the comment has average function

func EwmaSpeed
`func EwmaSpeed(unit int, unitFormat string, age float64, wcc ...WC) Decorator`

```
`unit` one of [0|UnitKiB|UnitKB] zero for no unit

`unitFormat` printf compatible verb for value, like "%f" or "%d"

`average` MovingAverage implementation

`wcc` optional WC config
```

**Comment by vbauerster** [comment]
Thank you for report, fixed in commit e806cc4.
