### ISSUE TITLE
Scrolling output above progress bars

### ISSUE THREAD

**Issue by sethkor** [vbauerster/mpb#44]
Hello,
Do you have an example where I can have a scrolling output above a progress bar?  I don't need it above each individual bar just above the progress.

Cheers
Seth

**Comment by vbauerster** [comment]
Hi, hope this [poplog](https://github.com/vbauerster/mpb/blob/master/_examples/poplog/main.go) example is what you want.

**Comment by sethkor** [comment]
Hi, 
Thanks, thats a great example but as I could have many 10,000s of lines I'm not sure it will perform well.

**Comment by sethkor** [comment]
How about if I use the Container Option "WithOutput" and a single progress bar?  I could output to a stiring buffer and print that with some `\r`?

**Comment by vbauerster** [comment]
> How about if I use the Container Option "WithOutput" and a single progress bar? I could output to a string buffer and print that with some \r?

string buffer is not aware of [ANSI Escape sequences](http://ascii-table.com/ansi-escape-sequences.php), so they will be literally there.

**Comment by sethkor** [comment]
OK Thanks
