### ISSUE TITLE
Possible content corruption

### ISSUE THREAD

**Issue by falzm** [vbauerster/mpb#45]
Hi,

We're [investigating](https://github.com/exoscale/cli/issues/137) a weird content corruption in our S3-compatible CLI tool, which is using the [minio/minio-go](https://github.com/minio/minio-go)/v6 and mpb/v4 packages. We've opened [an issue at minio-go](https://github.com/minio/minio-go/issues/1124) to discuss the problem, and while performing tests we've found out that the content corruption is directly linked to the progress bar usage. Could you please have a look at this and point to us to a potential misuse of your package in our code? That'd be great to help ruling out possibilities :)

**Comment by vbauerster** [comment]
Hi, this lib doesn't alter `io` content by any means. It provides single [wrapper](https://github.com/vbauerster/mpb/blob/master/proxyreader.go) around `io.Reader` [here](https://github.com/vbauerster/mpb/blob/db5cf0f6752702970148015f3a58d70a4509bb29/bar.go#L139). This wrapper doesn't distinguish whether underlying `io.Reader` is upload or download.

**Comment by vbauerster** [comment]
I think my old comment [here](https://github.com/vbauerster/mpb/issues/26#issuecomment-443433521) could be related to your issue.

**Comment by falzm** [comment]
Thank you for your response. I wasn't implying your lib was actively altering the content, rather that a misuse of it could lead to the problem we're facing.

**Comment by vbauerster** [comment]
Possible misuse: it's strange that you have two readers both sharing single source, then passing those readers at the same time in one call:

 - [reader1](https://github.com/exoscale/cli/blob/53606fba7615fc5aa09b4df85a55b9784dac4f99/cmd/sos_upload.go#L182)
- [reader2](https://github.com/exoscale/cli/blob/53606fba7615fc5aa09b4df85a55b9784dac4f99/cmd/sos_upload.go#L186)

**Comment by falzm** [comment]
Do you mean that it should be the same reader used in both cases (the one returned by `bar.ProxyReader(f)`)?

**Comment by vbauerster** [comment]
I'm not sure, it's not clear for me why that `minio` call requires two readers. You may try to omit [line 186](https://github.com/exoscale/cli/blob/53606fba7615fc5aa09b4df85a55b9784dac4f99/cmd/sos_upload.go#L186), and replace `f` with `bar.ProxyReader(f)` at [line 182](https://github.com/exoscale/cli/blob/53606fba7615fc5aa09b4df85a55b9784dac4f99/cmd/sos_upload.go#L182).

**Comment by falzm** [comment]
Hi, just to let you know the issue has been fixed. You were on the right track, it was indeed caused by a wrong reader usage: https://github.com/exoscale/cli/pull/157

Thank you for your time!
