### ISSUE TITLE
ETA is not accurate; could use help

### ISSUE THREAD

**Issue by dsoprea** [vbauerster/mpb#46]
The ETA isn't working correctly. It's initially non-zero, but drops to zero and stays there for most of the duration. I have a wrapper around the`io.Reader` that iteratively provides counts and durations. The durations are in the microsecond range.

The documentation for the timing arguments is very terse and, simple person that I am, the examples don't expand the understanding in any way that'd help to debug. I'd appreciate some assistance.

Implementation (based on the example):

```
progress := mpb.New()

bar := progress.AddBar(
    fi.Size(),

    mpb.PrependDecorators(
        // display our name with one space on the right
        decor.Name(
            currentFilepath,
            decor.WC{W: len(currentFilepath) + 1, C: decor.DidentRight}),

        // replace ETA decorator with "done" message, OnComplete event
        decor.OnComplete(
            // ETA decorator with ewma age of 60, and width reservation of 4
            decor.EwmaETA(decor.ET_STYLE_GO, 60, decor.WC{W: 4}), "done",
        ),
    ),

    mpb.AppendDecorators(decor.Percentage()),
)

progressCb = func(n int, duration time.Duration, isEof bool) error {
    bar.IncrBy(n, duration)
    return nil
}
```

I'm trying to understand how the ETA is supposed to work, but it's not clear, at least to me, from the documentation.

Output:

```
$ time go run cmd/gozp/main.go -f /tmp/big.gzp file.mp4
file.mp4   0s [==============================================>-------------------------------] 60 %
^Csignal: interrupt

real	0m12.364s
user	0m12.862s
sys	0m0.356s
```

This has at least another ten or twenty seconds to go at the 60% mark, but it dropped to (0) right after starting.

**Comment by dsoprea** [comment]
Same thing with decompression:

```

**Comment by dsoprea** [comment]
It's because the decor.EwmaETA() decorators were only part of the OnComplete decorator, which came from both examples. Once I moved it to be a first-class argument to PrependDecorators, for both compression and decompression, it worked fine:

```
progressBar := progress.AddBar(
    0,

    mpb.PrependDecorators(
        // Add our name.
        decor.Name(
            relFilepath,

            // Add space after the name.
            decor.WC{W: len(relFilepath) + 1, C: decor.DidentRight}),

        decor.Counters(
            decor.UnitKB,
            " %d/%d ",
        ),

        decor.EwmaETA(decor.ET_STYLE_MMSS, 60),
    ),

    mpb.AppendDecorators(
        decor.Percentage(),
    ),
)
```

It also took me a couple of passes to understand why the size/progress of the bar would jump near the end. It seemed like a math glitch somewhere (whether the user's or this project's). It looks like that's just the progress bars doing lazy syncing of their sizes. Is there someway that I can get bars to be correctly sized from the beginning to prevent the slight resizing that happens near the end?

**Comment by vbauerster** [comment]
Hi!
The key point for EwmaETA decorator to work correctly is family of Incr methods:

 - [Increment](https://godoc.org/github.com/vbauerster/mpb#Bar.Increment)
 - [IncrBy](https://godoc.org/github.com/vbauerster/mpb#Bar.IncrBy)
 - [IncrInt64](https://godoc.org/github.com/vbauerster/mpb#Bar.IncrInt64)

You have to pass incremental duration as second parameter.
Following snippet shows correct usage, notice that `start` var is set inside for loop, not outside.

```go
for {
  start := time.Now()
  // actual work, where you get writtenCount
  progressBar.IncrBy(writtenCount, time.Since(start))
}
```
It's not clear from your snippets how do you calculate duration for `IncrBy` method, but it looks like you set your `start` var outside of loop.
Also fyi, there is [AverageETA](https://godoc.org/github.com/vbauerster/mpb/decor#AverageETA) decorator, which doesn't require duration to be passed.

**Comment by vbauerster** [comment]
There is a [TimeNormalizer](https://godoc.org/github.com/vbauerster/mpb/decor#TimeNormalizer) option you can use with [MovingAverageETA](https://godoc.org/github.com/vbauerster/mpb/decor#MovingAverageETA), see example [here](https://github.com/vbauerster/getparty/blob/46b3277fc1a48950ee852cc7c89edbc44a6127ac/part.go#L68).
[EwmaETA](https://godoc.org/github.com/vbauerster/mpb/decor#EwmaETA) is a wrapper of [MovingAverageETA](https://godoc.org/github.com/vbauerster/mpb/decor#MovingAverageETA) with no [TimeNormalizer](https://godoc.org/github.com/vbauerster/mpb/decor#TimeNormalizer). It is crucial for any `ewma` based decorator to supply correct age parameter. I recommend to refer to [ewma](https://github.com/VividCortex/ewma) lib, which is used under the hood, in order to understand what age is.
