### ISSUE TITLE
Add a non zero init value for bars

### ISSUE THREAD

**Issue by Liupold** [vbauerster/mpb#47]
A non zero init value will be really helpful, As it would make the average speed and eta more accurate for resume able task. Hope I can convey my thoughts clearly.

**Comment by vbauerster** [comment]
Hi! I know what you mean, because I faced the same issue in my [getparty](https://github.com/vbauerster/getparty) project, but was a bit lazy to undertake something without a good push. So thank you for your observation, I'll make sure to fix this.

**Comment by vbauerster** [comment]
It's possible now to pass user defined start time with following constructor functions:
 - [NewAverageETA](https://godoc.org/github.com/vbauerster/mpb/decor#NewAverageETA)
 - [NewAverageSpeed](https://godoc.org/github.com/vbauerster/mpb/decor#NewAverageSpeed)

Or update all average decorators afterwards with:
 - [AdjustAverageDecorators](https://godoc.org/github.com/vbauerster/mpb#Bar.AdjustAverageDecorators)

Example usage is [here](https://github.com/vbauerster/getparty/blob/e893ef29069bc0eebb9d9749fc36eae92f60c1e5/part.go#L199).

**Comment by Liupold** [comment]
Thanks a lot, for this quick response.
