### ISSUE TITLE
Can I stop bar completing while total still being calculated

### ISSUE THREAD

**Issue by sethkor** [vbauerster/mpb#48]
Hello,
Is it possible to prevent a bar from completing until the final total is set?

My problem is the code to determine size is slower than the code to process items so the bar completes before I have a chance to set the final total.

In the interim I have worked around by artificially adding an extra item to the total at the start and then subtracting this at the end.

Cheers
Seth

**Comment by vbauerster** [comment]
Hello,
Bar [never completes](https://github.com/vbauerster/mpb/blob/35821d0017cc4e34e2b9f3dbe5624a7cc5b368da/bar.go#L259) if total set to zero.

**Comment by vbauerster** [comment]
Also fyi, you can trigger complete event manually with [SetTotal](https://godoc.org/github.com/vbauerster/mpb#Bar.SetTotal).

**Comment by sethkor** [comment]
Sorry I may not have been clear.  What I want is for complete event to not trigger if the bars current count equals the total.  In order to prevent this from happening now, I increment the total by 1 and then once I know it should complete I decrement total by 1 and set complete to true

**Comment by vbauerster** [comment]
Doesn't [this](https://github.com/vbauerster/mpb/blob/master/_examples/dynTotal/main.go) example suit your needs?
