### ISSUE TITLE
Close progress bar

### ISSUE THREAD

**Issue by mjshariati98** [vbauerster/mpb#49]
how close progress bar (stop rendering) without close whole program ?

**Comment by vbauerster** [comment]
Hi! What do you mean by saying `without closing whole program`?
You can use one of those:

 - [func (b *Bar) Abort(drop bool)](https://godoc.org/github.com/vbauerster/mpb#Bar.Abort)
 - [func (b *Bar) SetTotal(total int64, complete bool)](https://godoc.org/github.com/vbauerster/mpb#Bar.SetTotal)
 - [func PopCompletedMode() ContainerOption](https://godoc.org/github.com/vbauerster/mpb#PopCompletedMode)
