### ISSUE TITLE
How to update starting point (resumed downloads)

### ISSUE THREAD

**Issue by blacktop** [vbauerster/mpb#51]
How do I set the starting point for use with resumed downloads?

```go
	p := mpb.New(
		mpb.WithWidth(60),
		mpb.WithRefreshRate(180*time.Millisecond),
	)

	bar := p.AddBar(d.size, mpb.BarStyle("[=>-|"),
		mpb.PrependDecorators(
			decor.CountersKibiByte("\t% 6.1f / % 6.1f"),
		),
		mpb.AppendDecorators(
			decor.EwmaETA(decor.ET_STYLE_MMSS, float64(d.size)/2048),
			decor.Name(" ] "),
			decor.AverageSpeed(decor.UnitKiB, "% .2f"),
		),
	)

	if d.canResume {
		bar.SetCurrent(d.bytesResumed )
	}
	// create proxy reader
	reader := bar.ProxyReader(resp.Body)
	defer reader.Close()
```

```bash
   • resuming a previous download of: iPhone12_1_13.1.1_17A854_Restore.ipsw
	1.1 GiB /    0 b [----------------------------------------------------------| -48:-3 ] 71.44 MiB/s
```

See the total byte sits at 0b and the estimated time is negative??

Thank you!

**Comment by blacktop** [comment]
My mistake I was setting the total incorrectly.  

Thanks for such a great lib!

**Comment by vbauerster** [comment]
You can indicate resume visually with [SetRefill](https://godoc.org/github.com/vbauerster/mpb#Bar.SetRefill) method, [example](https://github.com/vbauerster/mpb/blob/master/_examples/suppressBar/main.go#L44).
PS: you're welcome!

**Comment by blacktop** [comment]
Is there a way to prevent the BPS from jumping up SUPER high when you resume?

When I resume it thinks I'm getting 3Gbs of bandwidth, but then it sloooooooowly resets the average back down to what it actually is?

**Comment by vbauerster** [comment]
- [AdjustAverageDecorators](https://godoc.org/github.com/vbauerster/mpb#Bar.AdjustAverageDecorators), related #47
 - or use `ewma` based speed decorator, it doesn't suffer from this issue.

**Comment by blacktop** [comment]
`decor.EwmaSpeed(decor.UnitKiB, "% .2f", (float64(d.size)/2048), decor.WCSyncSpace),` works great thanks!
