### ISSUE TITLE
Title width caclulation incorrect when using colored text

### ISSUE THREAD

**Issue by nektro** [vbauerster/mpb#53]
![image](https://user-images.githubusercontent.com/5464072/69493349-dd03c700-0e7b-11ea-98ac-ecc942ca52c7.png)

**Comment by vbauerster** [comment]
Hi!
Check out [stipansi](https://github.com/vbauerster/mpb/tree/stripansi) branch, please.
Should be fixed there, though didn't check on windows os.

**Comment by nektro** [comment]
worked for me too, though I don't have a Windows install to test it on.

**Comment by vbauerster** [comment]
Thanks for feedback! I'll merge it into master soon.

**Comment by nektro** [comment]
Thank you! :)
