### ISSUE TITLE
Add width option that allows Decorator to be cut off in its length

### ISSUE THREAD

**Issue by nektro** [vbauerster/mpb#55]
This issue has popped up due to the fact that the way I use mpb I don't always know the exact titles that are going to be on all the bars I use, namely URLs. This leads to a situation where the line overflows and then the erase/redraw isn't clean and repeats a bunch of lines until the bar is finished/removed.

So being able to set a particular decorator as 'able to be cropped' would be very handy.

(If you're unsure of what I'm referring to I can try and reproduce and at screenshots at a later time.)

**Comment by vbauerster** [comment]
Yes please screenshot would be helpful.

**Comment by nektro** [comment]
![image](https://user-images.githubusercontent.com/5464072/80674285-706ea300-8a7f-11ea-8fce-a98dd47dcea0.png)

**Comment by nektro** [comment]
![image](https://user-images.githubusercontent.com/5464072/80685918-e67e0480-8a95-11ea-8722-6e96c1d7a043.png)

**Comment by vbauerster** [comment]
There is such [option](https://github.com/vbauerster/mpb/blob/e8bb1ffc94a11a12d65a1a1647bd4df1acfafbc9/decor/decorator.go#L120) which is effective if no any `WCsync... = DSyncWidth` involved. `WCsync...` option means sync width among multiple bars of the same column decorator. If you still want to limit width in that case (allow width sync among same column decorators, but limit it by some value), you can use something like following:

```go
func LimitWidthDecorator(str string, limit int, wcc ...decor.WC) decor.Decorator {
	format := fmt.Sprintf("%%.%ds", limit)
	return decor.Any(func(*decor.Statistics) string {
		return fmt.Sprintf(format, str)
	}, wcc...)
}
```

**Comment by nektro** [comment]
I'm not trying to set a max width for a column, in this particular case I want to be able to say that the title decorator's (the one with the url in this case) length is not important. This way, if mpb goes to print a line and determines that it is wider than the current terminal, it can be shrunk, just as the progress bar itself has in the pictures above.

**Comment by vbauerster** [comment]
I've refactored [decor.Statistics](https://github.com/vbauerster/mpb/blob/1dd7643c9fbc4e605644c1e914f6c03c88e98099/decor/decorator.go#L54-L55) to include two new fields `OccupiedWidth` and `TermWidth`. So basically you can do something like following, hope it helps.

```go
fn := func(s decor.Statistics) string {
	longString := getLongStringFromSomewhere()
	if s.OccupiedWidth + utf8.RuneCountInString(longString) > s.TermWidth {
		// need to cut longString here,
		// but leave some space for the bar, otherwise it will be shrinked
		availableWidth := s.TermWidth - s.OccupiedWidth
		//cutString, so its final len is less than availableWidth
		return cutStrting
	}
	return longString
}
// convert fn to decorator
decor.Any(fn, decor.WCsyncWidth)
```

**Comment by nektro** [comment]
Will update and check this out, thanks!

**Comment by vbauerster** [comment]
I've changed [decor.Statistics](https://github.com/vbauerster/mpb/blob/357d30f8e4a98824bdf8ea172af7d1a86956d013/decor/decorator.go#L54), so aforementioned snippet should now look like this:
```go
fn := func(s decor.Statistics) string {
	longString := getLongStringFromSomewhere()
	if utf8.RuneCountInString(longString) > s.AvailableWidth {
		// need to cut longString, so it's less than s.AvailableWidth
		return cutStrting
	}
	return longString
}
// convert fn to decorator
decor.Any(fn, decor.WCsyncWidth)
```

**Comment by vbauerster** [comment]
So you can either manually track and limit decorator's width as described above, or don't take any action at all. In latter case decorator's part will be truncated:

[![Screenshot-2020-05-15-at-13-42-47.png](https://i.postimg.cc/J4zN86kw/Screenshot-2020-05-15-at-13-42-47.png)](https://postimg.cc/nMNjY12T)
Here `PrependDecorators` have been truncated ↑.

[![Screenshot-2020-05-15-at-13-43-42.png](https://i.postimg.cc/rpV0GzCB/Screenshot-2020-05-15-at-13-43-42.png)](https://postimg.cc/JsFzMrFx)
Here `AppendDecorators` have been truncated ↑.
