### ISSUE TITLE
Be able to update decorator text

### ISSUE THREAD

**Issue by nektro** [vbauerster/mpb#57]
Right now there is no way to update the bar title or any decorator text, only change their configs.

Additionally, `decor.CBFunc` takes no index, so you have no idea which decorating with Bar.TraverseDecorators.

**Comment by vbauerster** [comment]
Decorators like percentage and eta for example are meant to be fixed format.
Do you want to have something like `decor.Name` but with ability to set any text while bar is rendering?

As for `decor.CBFunc` I don't see any reason why it should provide index.

**Comment by nektro** [comment]
![image](https://user-images.githubusercontent.com/5464072/73754737-dd012c80-4732-11ea-8bbf-407fbc716d8e.png)

sparing the bad function name, I have this to generate a bar and the request was so that I could something like the following and update the last decorator

![image](https://user-images.githubusercontent.com/5464072/73754912-2baec680-4733-11ea-8254-226fd774fff4.png)

**Comment by nektro** [comment]
if you're wondering "why create a Bar with a total of 1" it's because I have other methods with a similar utility

![image](https://user-images.githubusercontent.com/5464072/73755142-952ed500-4733-11ea-99e1-1fd5bc20b241.png)

**Comment by vbauerster** [comment]
I did some refactoring. You can use [Any](https://github.com/vbauerster/mpb/blob/c0b52b31e85a598603c182ddf6501c5d91937e24/decor/any.go#L10) decorator in order to update decorator's text when needed.

**Comment by vbauerster** [comment]
Also, refer to pattern used in [on_complete.go](https://github.com/vbauerster/mpb/blob/master/decor/on_complete.go). You can override any existing decorator by using that pattern.
