### ISSUE TITLE
Clear spinner on complete

### ISSUE THREAD

**Issue by akshaybabloo** [vbauerster/mpb#58]
Is there a way to clear the spinner after complete? Like the one for bar using `mpb.BarClearOnComplete()`

**Comment by vbauerster** [comment]
`mpb.BarClearOnComplete()` works with spinner filler and it's shortcut for `mpb.BarOnComplete("")`. By spinner filler I mean the bar you get with `*Progress.AddSpinner(...) *Bar`.
