### ISSUE TITLE
ewma time going up?

### ISSUE THREAD

**Issue by sedlund** [vbauerster/mpb#59]
I must be doing something wrong, I'm hoping someone can spot it easily and help me out.

https://asciinema.org/a/emiUqPl3r9mIrj9CudPv0fJa3

The data below the bar is what I was calculating myself before finding this neat progress bar, but the eta on the bar seems to be going the wrong way fast?

code:
https://gist.github.com/sedlund/dd27e52a21b443713eb7ece80d35d3d4

**Comment by vbauerster** [comment]
Hi!
`start := time.Now()` at line 137, must be moved inside for loop. EWMA's unit of measure is an iteration's taken time. [example](https://github.com/vbauerster/mpb/blob/6da9e03c4c895b0be033d86e868b3b6f2e2ddab5/_examples/singleBar/main.go#L35). Also all those `decor.WCSync...` aren't necessary for single bar usage.

**Comment by sedlund** [comment]
Thanks!

I found that I also needed to slow my poll as well by inserting a sleep:

		time.Sleep(time.Millisecond * 1000)
		bar.SetCurrent(int64(curFrame), time.Since(start))

**Comment by vbauerster** [comment]
Not a problem!
There is an average eta decorator available as well, which doesn't require to pass any duration into `bar.SetCurrent`.
