### ISSUE TITLE
Add width options that makes decorator remember width for short time

### ISSUE THREAD

**Issue by nektro** [vbauerster/mpb#60]
With my library that I primarily to use to make web scrapers, there are two main types of bars. those being manual value ones and download ones. and as the byte formatting makes the counter column much wider than normal as shown below.

![image](https://user-images.githubusercontent.com/5464072/78229090-83e91700-749d-11ea-9648-47444fd070ad.png)

![image](https://user-images.githubusercontent.com/5464072/78229111-8c415200-749d-11ea-880f-fdcb11240147.png)

however, as many downloads may appear and disappear but a parent bar, this width difference can cause it to be very spam-y and make that column hard to read.

therefore I was hoping it would be possible to be able to tell mpb that the width of that column should be remembered shortly (perhaps 1s) before shrinking. currently I use `decor.WCSyncWidth`.

**Comment by vbauerster** [comment]
Sorry I didn't quite understand what the problem is. Can you please post some snippet where this issue is reproducible? As a last resort you can always implement your own decorator if built-in doesn't meet your needs.
