### ISSUE TITLE
Please consider an actual code license, like BSD-3-Clause, instead of Unlicense

### ISSUE THREAD

**Issue by ahkok** [vbauerster/mpb#61]
Unlicense is a type of Public Domain attribution that has significant legal issues due to local rules about Public Domain status, and may actually make it difficult for people to use or contribute.

Looking back at the history of this project, it actually was BSD-3-Clause before, which does not have these legal issues. Frankly that's a major step back. Going to BSD-2-Clause would have been better, MIT/ISC too.

I would strongly urge you to pick a real code license and not a PD attribution-like license. MIT/BSD's are all fine, Apache-2.0 would be fine, but Unlicense and other PD attributions should be avoided.

Disclaimer: IANAL

**Comment by vbauerster** [comment]
Hello, thank you for your interest. I will keep this project under Unlicense.

Users who have significant legal issues can either use previous version of `mpb` or fork current version. As a last resort there are other similar projects with "actual" licenses they may consider to use, to name a few:

https://github.com/cheggaaa/pb
https://github.com/schollz/progressbar
https://github.com/gosuri/uiprogress
