### ISSUE TITLE
non-complete bar says 100%

### ISSUE THREAD

**Issue by nektro** [vbauerster/mpb#64]
```
Task 47 : 1881 / 1885 [================================]  100 %:    00:06:
```

This is in reference to the `1881 / 1885` which is calculated with using
`decor.CountersNoUnit("%d / %d", decor.WCSyncWidth),`

**Comment by vbauerster** [comment]
That is expected if you use [Percentage](https://github.com/vbauerster/mpb/blob/4c55328a4521cea0ff1f2fd646c292d14da0298f/decor/percentage.go#L36) decorator which defaults to zero precision. If you need non-zero percentage precision use [NewPercentage](https://github.com/vbauerster/mpb/blob/4c55328a4521cea0ff1f2fd646c292d14da0298f/decor/percentage.go#L49) instead.

https://play.golang.org/p/y1sDAIYDxl2

You may need to initialize percentage like [this](https://github.com/vbauerster/getparty/blob/f820d00b6b12f1de208ae198b0d29906dbf1f3d9/part.go#L58).

**Comment by nektro** [comment]
This works, thanks so much for the pointer. :heart:
