### ISSUE TITLE
Sometimes a bar fails to clear after completing and calling `Wait`

### ISSUE THREAD

**Issue by cipriancraciun** [vbauerster/mpb#68]
Although I've used `BarRemoveOnComplete` on `AddBar`, I am making sure `SetTotal` and `SetCurrent` are correctly set to be completed, and I'm waiting for `Wait` to complete, sometimes the bar fails to be removed after completion.

Through experimentation, I've observed that waiting after `Wait` the same amount of time (plus some extra) as I've set with `mpb.WithRefreshRate`, seems to solve the issue.

This makes me think there is perhaps a race condition happening inside `Wait`?

**Comment by cipriancraciun** [comment]
Based on some further experimentation it seems that although after `Wait` returns there are no more goroutines running (except the main one), in some cases the bar still is not removed, which points away from a potential race condition in the code, and towards a "logic" issue.

I have also made sure to `os.Stderr.Sync ()` (which I've used for `WithOutput`), so the issue is not buffering.

**Comment by vbauerster** [comment]
Thanks for reporting! Can you please check on latest master? I just pushed commits, which should fix this.

**Comment by cipriancraciun** [comment]
Yes, I can confirm that by using the latest commit the issue seems to be solved: https://github.com/vbauerster/mpb/commit/dc22c1ba454298ef392acdc1e720a905ab809974

Thanks!  I'll close this issue.  (If it resurfaces, I'll reopen it again.)
