### ISSUE TITLE
Set bar-text dynamically after completing

### ISSUE THREAD

**Issue by JojiiOfficial** [vbauerster/mpb#71]
Is it possible to set the text of the progressbar after calling the "AddBar" func? Lets assume I want to upload a file. After uploading I receive data from a server where the file was uploaded to. How can I set the "OnComplete" text of the bar dynamically after the file is uploaded?

**Comment by vbauerster** [comment]
Progress bar is structured like this:
```
[Decorator1..DecoratorN] [BarFiller] [Decorator1..DecoratorN]
```

To replace `BarFiller` with some string on completion, use [BarFillerOnComplete](https://github.com/vbauerster/mpb/blob/a55da8df10b6d8d8172eea63c25e65bf975806d6/bar_option.go#L79) option.
If you need something more advanced use [BarFillerMiddleware](https://github.com/vbauerster/mpb/blob/a55da8df10b6d8d8172eea63c25e65bf975806d6/bar_option.go#L92) option.

For decorators there is similar option named [decor.OnComplete](https://github.com/vbauerster/mpb/blob/a55da8df10b6d8d8172eea63c25e65bf975806d6/decor/on_complete.go#L10).

**Comment by JojiiOfficial** [comment]
Exactly what I was looking for. Thank you!
