### ISSUE TITLE
Missing package

### ISSUE THREAD

**Issue by qingfeng20188** [vbauerster/mpb#72]
github.com/vbauerster/mpb/v5  is missing and not found?

**Comment by vbauerster** [comment]
Hello, can you please elaborate on this? Where do you get this from?

**Comment by milan60** [comment]
Use `go get github.com/vbauerster/mpb` that did the trick for me

**Comment by vbauerster** [comment]
@qingfeng20188 
`github.com/vbauerster/mpb/v5` is available as a go module, so to get v5 issue `go mod init` first.

@milan60 
with `go get github.com/vbauerster/mpb` I'm getting old version and there is no any missing package error.
