### ISSUE TITLE
Bar not removed after context canceled in interactive shell

### ISSUE THREAD

**Issue by Prnyself** [vbauerster/mpb#77]
I try to use progress bar in [go-prompt](https://github.com/c-bata/go-prompt)，it works well when task completed itself. But, if I interrupted the task by `Ctrl + C` and canceled the context (used to create the progress by `NewWithContext`), the progress bar still keeps rendering in my shell, even if I can input new cmd and run it.

**Comment by Prnyself** [comment]
And it is possible in some condition that after task done, the bar is still rendering just like canceled mentioned above.

**Comment by Prnyself** [comment]
Whoops, I've found what I missed. I didn't call `Wait()` when context canceled. So the progress did not shutdown. By the way, maybe consider to make `shutdown()` a public method cuz 'shutdown' is quite not familiar with 'wait'?

**Comment by vbauerster** [comment]
Glad you solved it.

> By the way, maybe consider to make shutdown() a public method cuz 'shutdown' is quite not familiar with 'wait'?

Wait method doesn't shutdown the progress pool, it just waits until underlying bars are completed and completion could be triggered ether by normal `current == total` or by cancel context.
