### ISSUE TITLE
Question: Possible to change UNLICENSE file to LICENSE?

### ISSUE THREAD

**Issue by MarlonGamez** [vbauerster/mpb#78]
Hi, I was wondering if it would be possible to change the license file name from UNLICENSE to LICENSE. I work on [skaffold](https://github.com/GoogleContainerTools/skaffold), and we use [go-licenses](https://github.com/google/go-licenses) to check the licenses of dependencies used in the project. The go-licenses tool tries to find files in the repo using a regexp "^(LICEN(S|C)E|COPYING|README|NOTICE)(\\..+)?$", and unfortunately this skips over your UNLICENSE file. 

I'm very interested in trying your library in our project :)

**Comment by eclipseo** [comment]
Can't go-licenses update is regex? I use this in Python, derived from Rust ripgrep:

matcher = re.compile(
        r"(COPYING|COPYING[\.\-].*|COPYRIGHT|COPYRIGHT[\.\-].*|"
        r"EULA|EULA[\.\-].*|licen[cs]e|licen[cs]e.*|LICEN[CS]E|"
        r"LICEN[CS]E[\.\-].*|.*[\.\-]LICEN[CS]E.*|NOTICE|NOTICE[\.\-].*|"
        r"PATENTS|PATENTS[\.\-].*|UNLICEN[CS]E|UNLICEN[CS]E[\.\-].*|"
        r"agpl[\.\-].*|gpl[\.\-].*|lgpl[\.\-].*|AGPL-.*[0-9].*|"
        r"APACHE-.*[0-9].*|BSD-.*[0-9].*|CC-BY-.*|GFDL-.*[0-9].*|"
        r"GNU-.*[0-9].*|GPL-.*[0-9].*|LGPL-.*[0-9].*|MIT-.*[0-9].*|"
        r"MPL-.*[0-9].*|OFL-.*[0-9].*)")

**Comment by MarlonGamez** [comment]
That's true, I've opened an issue/PR on their repo as well. I'll leave this issue open still as it might be resolved quicker through here

**Comment by vbauerster** [comment]
I'd like to keep UNLICENSE file, so there is no confusion. Though I'm fine with making a symlink to it, if that will make go-licenses happy.

**Comment by MarlonGamez** [comment]
@vbauerster It seems like go-licenses isn't liking symlinks (at least from my testing). I can try and see if I can get them to support them

**Comment by vbauerster** [comment]
I think that is ok to have second license file with the same content as in UNLICENSE, can you pls update your PR?
