### ISSUE TITLE
wishlist: mix line-based output with progress bar status

### ISSUE THREAD

**Issue by anguslees** [vbauerster/mpb#8]
I haven't seen an obvious way to do this with mpb, but I'd love to be able to print line-based output ("Downloaded file a\nDownloaded file b\n" etc) while also having a progress bar.

Ideally this would be presented as an io.Writer so I can plug it into existing code that is expecting to just write non-atomically directly to stdout.

**Comment by vbauerster** [comment]
Is printing final messages right in decorator isn't an option for you?
For example you can implement your own custom decorator which will behave like this:
```
counters or whatever [===>---] 50%
Downloaded file x [=======] 100%
```

**Comment by vbauerster** [comment]
I have added [OutputInterceptors](https://godoc.org/github.com/vbauerster/mpb#OutputInterceptors) ProgressOption. You can provide your `func(io.Writer)`, which will called each render cycle.

**Comment by ficoos** [comment]
There is no `WithInterceptors` how are we supposed to accomplished?
Keeping the completed bars is not an options as they will be redrawn and I have thousands of them.
Further more, I would like to just log while the progress is happening at the bottom.

**Comment by vbauerster** [comment]
Hi! I think it was renamed to [BarNewLineExtend](https://godoc.org/github.com/vbauerster/mpb#BarNewLineExtend) option. Related [example](https://github.com/vbauerster/mpb/blob/master/examples/barNewLineExtend/main.go#L31).

**Comment by ficoos** [comment]
I looked at that, it just adds a line after the current bar. It's still part of the output that `Progress` writes when it renders. This means that when you have thousands of lines `Progress` needlessly renders those thousands of lines again. I just want it to print the line and continue on below.
