### ISSUE TITLE
Cannot complete automatically after use bar.SetTotal.

### ISSUE THREAD

**Issue by Leavrth** [vbauerster/mpb#97]
It seems that this bar cannot trigger complete by `Increment()` function, after run `bar.SetTotal(total, false)`.

Why not let it runs as before instead of `forceRefreshIfLastUncompleted`, when `current < total` after do `bar.SetTotal(total, true)`.

**Comment by vbauerster** [comment]
It's by design. If `bar.SetTotal(total, false)` has been called, triggering complete is disabled until `bar.SetTotal(total, true)` is called.
